services:
  node:
    build: .
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
      - packages_node_modules:/app/packages/my-library/node_modules
      - apps_maxmsp_test_node_modules:/app/apps/maxmsp-test/node_modules
volumes:
  app_node_modules:
  packages_node_modules:
  apps_maxmsp_test_node_modules:
